// Section definitions for New Enrollment wizard (for modularity and future dynamic rendering)
export const sections = [
  {
    key: "studentInfo",
    title: "Student Basic Information",
    required: true,
    fields: [
      { name: "first_name", label: "First Name", type: "text", required: true },
      { name: "last_name", label: "Last Name", type: "text", required: true },
      { name: "other_names", label: "Other Names", type: "text" },
      { name: "gender", label: "Gender", type: "select", required: true, options: ["Male", "Female", "Other"] },
      { name: "date_of_birth", label: "Date of Birth", type: "date", required: true },
      { name: "national_id", label: "National ID / Birth Certificate No", type: "text" },
      { name: "student_photo", label: "Student Photo", type: "file", accept: "image/*" },
      { name: "nationality", label: "Nationality", type: "text" },
      { name: "religion", label: "Religion", type: "text" },
      { name: "languages", label: "Language(s) Spoken", type: "text" },
    ],
    system: [
      "Age auto-calculated from DOB",
      "Age validation per institution type",
      "Duplicate detection (name + DOB)",
    ],
  },
  {
    key: "enrollmentDetails",
    title: "Enrollment Details",
    required: true,
    fields: [
      { name: "academic_year", label: "Academic Year", type: "text", required: true },
      { name: "term", label: "Term", type: "text", required: true },
      { name: "class_grade", label: "Class / Grade", type: "text", required: true },
      { name: "stream", label: "Stream / Section", type: "text" },
      { name: "admission_type", label: "Admission Type", type: "select", options: ["New", "Transfer", "Returning"] },
      { name: "intake", label: "Intake (Jan / May / Aug)", type: "select", options: ["Jan", "May", "Aug"] },
      { name: "faculty", label: "Faculty", type: "text" },
      { name: "program", label: "Program", type: "text" },
      { name: "mode_of_study", label: "Mode of Study", type: "select", options: ["Full-time", "Part-time", "Distance"] },
    ],
    system: [
      "Capacity check (class/program)",
      "Prevent over-enrollment",
      "Show available slots",
    ],
  },
  {
    key: "guardianInfo",
    title: "Parent / Guardian Information",
    required: true,
    fields: [
      { name: "guardian1_full_name", label: "Guardian 1 Full Name", type: "text", required: true },
      { name: "guardian1_relationship", label: "Relationship", type: "text", required: true },
      { name: "guardian1_phone", label: "Phone Number", type: "text", required: true },
      { name: "guardian1_email", label: "Email", type: "email" },
      { name: "guardian1_occupation", label: "Occupation", type: "text" },
      { name: "guardian1_address", label: "Physical Address", type: "text" },
      { name: "guardian2_full_name", label: "Guardian 2 Full Name", type: "text" },
      { name: "guardian2_relationship", label: "Relationship", type: "text" },
      { name: "guardian2_phone", label: "Phone Number", type: "text" },
      { name: "guardian2_email", label: "Email", type: "email" },
      { name: "guardian2_occupation", label: "Occupation", type: "text" },
      { name: "guardian2_address", label: "Physical Address", type: "text" },
    ],
    system: [
      "One guardian can link to multiple students",
      "Auto-create guardian account",
      "SMS/Email verification",
    ],
  },
  {
    key: "contactAddress",
    title: "Contact & Address Information",
    required: true,
    fields: [
      { name: "home_address", label: "Home Address", type: "text", required: true },
      { name: "district_city", label: "District / City", type: "text", required: true },
      { name: "country", label: "Country", type: "text", required: true },
      { name: "emergency_contact_name", label: "Emergency Contact Name", type: "text", required: true },
      { name: "emergency_contact_phone", label: "Emergency Contact Phone", type: "text", required: true },
    ],
  },
  {
    key: "academicBackground",
    title: "Previous School / Academic Background",
    required: false,
    fields: [
      { name: "previous_school_name", label: "Previous School Name", type: "text" },
      { name: "last_class_completed", label: "Last Class Completed", type: "text" },
      { name: "reason_for_transfer", label: "Reason for Transfer", type: "text" },
      { name: "previous_institution", label: "Previous Institution", type: "text" },
      { name: "highest_qualification", label: "Highest Qualification", type: "text" },
      { name: "index_number", label: "Index / Registration Number", type: "text" },
      { name: "certificates", label: "Uploaded Certificates / Transcripts (PDF)", type: "file", accept: ".pdf" },
    ],
  },
  {
    key: "healthSpecialNeeds",
    title: "Health & Special Needs",
    required: false,
    fields: [
      { name: "medical_conditions", label: "Medical Conditions", type: "text" },
      { name: "allergies", label: "Allergies", type: "text" },
      { name: "disabilities", label: "Disabilities / Special Needs", type: "text" },
      { name: "accommodations", label: "Required Accommodations", type: "text" },
      { name: "doctor_notes", label: "Doctor / Emergency Notes", type: "text" },
    ],
    system: [
      "Role-restricted visibility",
      "Audit logs for access",
    ],
  },
  {
    key: "feeBilling",
    title: "Fee & Billing Setup",
    required: true,
    fields: [
      { name: "fee_structure", label: "Fee Structure", type: "text", required: true },
      { name: "scholarship_discount", label: "Scholarship / Discount", type: "text" },
      { name: "payment_plan", label: "Payment Plan", type: "select", options: ["Full", "Installments"] },
      { name: "initial_payment", label: "Initial Payment Amount", type: "number" },
      { name: "payment_method", label: "Payment Method", type: "select", options: ["Cash", "Mobile Money", "Bank", "Card"] },
    ],
    system: [
      "Auto-generate invoice",
      "Ledger entry",
      "Partial payment support",
      "Outstanding balance tracking",
    ],
  },
  {
    key: "documentsUpload",
    title: "Documents Upload",
    required: false,
    fields: [
      { name: "birth_certificate", label: "Birth Certificate / ID", type: "file", accept: ".pdf,.jpg,.jpeg,.png" },
      { name: "transfer_letter", label: "Transfer Letter", type: "file", accept: ".pdf,.jpg,.jpeg,.png" },
      { name: "academic_reports", label: "Academic Reports", type: "file", accept: ".pdf,.jpg,.jpeg,.png" },
      { name: "passport_photo", label: "Passport Photo", type: "file", accept: ".jpg,.jpeg,.png" },
      { name: "medical_report", label: "Medical Report", type: "file", accept: ".pdf,.jpg,.jpeg,.png" },
    ],
    system: [
      "File type & size validation",
      "Preview before submit",
      "Secure storage",
    ],
  },
  {
    key: "accountAccess",
    title: "Account & Access Setup",
    required: false,
    fields: [
      { name: "student_id", label: "Student ID / Reg No", type: "text" },
      { name: "portal_email", label: "Student Portal Email", type: "email" },
      { name: "portal_username", label: "Student Portal Username", type: "text" },
      { name: "parent_portal_access", label: "Parent Portal Access", type: "checkbox" },
    ],
    system: [
      "Auto-generate Student ID / Reg No",
      "Create Student Portal Account",
      "Assign Email/Username",
      "Parent Portal Access toggle",
    ],
  },
  {
    key: "reviewConfirm",
    title: "Enrollment Review & Confirmation",
    required: true,
    fields: [
      { name: "confirmation", label: "I confirm this information is correct", type: "checkbox", required: true },
    ],
    system: [
      "Read-only summary view",
      "Highlight missing fields",
      "Save as Draft",
      "Submit & Enroll",
      "Submit & Await Approval",
    ],
  },
];
